version: '3.7'
services:
  xui:
    container_name: xui
    image: 'coporton/xtreamui:latest'
    shm_size: '1GB'
    privileged: true
    restart: unless-stopped
    ports:
      - '0.0.0.0:25462:25462'
      - '0.0.0.0:25461:25461'
      - '0.0.0.0:25463:25463'
      - '0.0.0.0:25464:25464'
      - '0.0.0.0:25465:25465'
      - '0.0.0.0:25500:25500'
    ulimits:
     nproc: 65535
    cap_add:
     - ALL
    command: ["supervisord", "--nodaemon", "--configuration", "/etc/supervisor/supervisord.conf"]
    volumes:
      - /opt/xtreamcodes/iptv_xtream_codes/logs:/home/xtreamcodes/iptv_xtream_codes/logs
      - /opt/xtreamcodes/iptv_xtream_codes/logs/supervisor:/var/log/supervisor
      - /opt/xtreamcodes/iptv_xtream_codes/mysql:/var/lib/mysql      
